name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint)
        run: npm run lint

      #  We dont have any test yet
      # - name: Run tests (Jest) 
      #   run: npm test

      - name: Build (Webpack)
        run: npm run build

      # This doesnt really work yet we need to figure this out
      # - name: Package Firefox Extension
      #   run: npm run build:ext

      - name: Generate docs (JSDoc)
        run: npm run docs

      # This doesnt work yet need to figure this out
      # - name: Upload extension artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: firefox-recap-extension
      #     path: web-ext-artifacts/*.zip